# file to configure the SQLC behavior
version: "1"
project:
    id: "postgres_sqlc_guide"
packages:
-   name: postgres
    path: "../"
    schema: "../schema/"
    queries: "../queries/"
    engine: "postgresql"
    emit_json_tags: true
    emit_interface: false
    emit_exact_table_names: false
    